### ISSUE TITLE
About— Standards & Submissions doc logo

### ISSUE THREAD

**Issue by MarcAst24** [healthyregions/chicago-environment-explorer#100]
**Issue**: In the link “Standards and Submission Guidelines”, is the logo a standard ChiVes logo?

**Recommendation**:  Either change it to text based title or formally use logo in webpage as well

**Rationale**: Consistency

**Comment by mradamcox** [comment]
@Makosak I think you're the best person with full edit permissions to this Google Doc to complete this task.

**Comment by mradamcox** [comment]
I have added the green circles logo to that document.
