### ISSUE TITLE
About—Core project team links

### ISSUE THREAD

**Issue by MarcAst24** [healthyregions/chicago-environment-explorer#104]
**Issue**: Links for core project team as well?

**Recommendation**: Add personal website/work portfolio/LinkedIn link to team members

**Rationale**: So that views can also connect with core contributors

**Comment by mradamcox** [comment]
We do have links in the code already [here](https://github.com/GeoDaCenter/chicago-environment-explorer/blob/main/src/components/Pages/About.js#L16), but these need to be vetted first before we put them on the page.
