### ISSUE TITLE
Contact Us—Cognitive load on form

### ISSUE THREAD

**Issue by MarcAst24** [healthyregions/chicago-environment-explorer#107]
**Issue**: Form seems to put some cognitive load

**Recommendation**:

- Remove box container border
- Adjust form fields to look more aligned:
  - Message field is taller to cover the height of the first three fields on the left
  - Submit button is in line with the fourth field on the left (phone number)

**Rationale**: Reduce cognitive load on form

**Comment by shubhamk008** [comment]
@mradamcox @bodom0015 not the most important issue but will be a plus if resolved. Can chat more if there are doubts.
