### ISSUE TITLE
Color palette suggestions for air quality variables and economic hardship

### ISSUE THREAD

**Issue by MStuhlmacher** [healthyregions/chicago-environment-explorer#166]
**Issue**
At our events in June, some of the community members who interacted with the air quality and economic hardship maps had trouble interpreting what colors represented high values vs. low values. For example, for the air quality maps, the darkest purple could be interpreted as the worst air quality while the lighter yellow could be interpreted as the best.

**Recommendation**
We recommend this color palette for economic hardship:
#feebe2
#fcc5c0
#fa9fb5
#f768a1
#c51b8a
#7a0177

And this color palette for all of the air quality variables:
#edf8fb
#bfd3e6
#9ebcda
#8c96c6
#8856a7
#810f7c

**Rationale**
Both of these palettes are colorblind friendly and are sequential which will help with the interpretation issues the current color palettes have.

**Comment by mradamcox** [comment]
This is now implemented, but here are the old color scales, just in case we need to revert for some reason:

economic hardship:
```
old: [[175, 240, 91], [226, 183, 47], [255, 120, 71], [254, 75, 131], [191, 60, 175], [110, 64, 170]]

new: [[254,235,226], [252,197,192], [250,159,181], [247,104,161], [197,27,138], [122,1,119]]
```
air quality variables:
```
old -- Satellite-Derived Particulate Matter (PM2.5): [[68, 1, 84],[70, 50, 127],[54, 92, 141],[39, 127, 142],[31, 161, 135],[74, 194, 109],[159, 218, 58],[253, 231, 37]]
old -- Observed Particulate Matter (PM2.5): [[70, 50, 127],[54, 92, 141],[39, 127, 142],[31, 161, 135],[74, 194, 109],[159, 218, 58]]
old -- Modeled Nitrogen Dioxide (NO2): [[68, 1, 84],[70, 50, 127],[54, 92, 141],[39, 127, 142],[31, 161, 135],[74, 194, 109],[159, 218, 58],[253, 231, 37]]
old -- Modeled Ozone (O3): [[68, 1, 84],[70, 50, 127],[54, 92, 141],[39, 127, 142],[31, 161, 135],[74, 194, 109],[159, 218, 58],[253, 231, 37]]
old -- Modeled Particulate Matter (PM2.5): [[68, 1, 84],[70, 50, 127],[54, 92, 141],[39, 127, 142],[31, 161, 135],[74, 194, 109],[159, 218, 58],[253, 231, 37]]

new: [[237,248,251], [191,211,230], [158,188,218], [140,150,198], [136,86,167], [129,15,124]]
```

**Comment by Makosak** [comment]
I don't agree with the air quality variable hues here, for multiple reasons -- it suggests areas with less pollution don't have any when visualized, and that's not consistent with what air quality advocates recommend. We went with Viridis based on extensive discussions with prior air quality metric contributors, highlighting "hot spots" with yellow. But I understand that this is an open issue; emailing all prior air quality contributors to discuss.

**Comment by Makosak** [comment]
Economic hardship looks good to me though -- That one has been updated!

**Comment by Makosak** [comment]
Summarizing the air quality metric constraints so far, please feel free to add more here @MStuhlmacher and others
- Non-stigmatizing colors (avoiding red when possible; only exception has been heat map for now)
- Colors should be saturated enough on both ends to highlight some level of pollution (low or high), as all are above 0
- Colors should be easy to interpret by a wide variety of community members and residents
- Colors should be color-blind safe and accessible (so easy to differentiate across the spectrum)

We had also tried plasma and magma, but wasn't always clear which direction is higher/lower: https://www.thinkingondata.com/something-about-viridis-library/

**Comment by Makosak** [comment]
To be updated with yellow palette proposed by team

**Comment by mradamcox** [comment]
Completed with #152
