### ISSUE TITLE
Histogram filtering is buggy

### ISSUE THREAD

**Issue by Makosak** [healthyregions/chicago-environment-explorer#170]
When updating histogram filters on the right hand side, they stop at what seems like arbitrary breaks, and it's not clear what # they've stopped on. We'll need to refine this a bit more:

- Add more breaks/places for the filter to be stopped in the histogram
- Specify what number is being filtered somewhere within the histogram UI (so the user knows what threshold is being used)

Potentially, the number being selected for the filter can be shown _underneath_ the histogram, on the left hand side. Later on we could add an indicator if this number is "low" "med" high" within the same line, on the right hand side.

**Comment by mradamcox** [comment]
Just clicking around a bit with it, seems to be snapping to divisions of tenths, which doesn't correspond to what's shown visually.

**Comment by mradamcox** [comment]
Desired updates for these filters:
- Show the number (raw data value) that a filter line is set on
- Ideal: disable snapping/steps altogether (only have smooth sliding)
  - Alternatively, choosing a much smaller resolution, like 100 steps, would be sufficient as well.

Down the road it would also be nice to preset certain snap locations based on the top of significant data curves, etc. But, for now, the above solutions will be sufficient.
