### ISSUE TITLE
Create (and document) new Resource Overlays sheet

### ISSUE THREAD

**Issue by mradamcox** [healthyregions/chicago-environment-explorer#173]
As we are adding more layers to the map that don't fit the original design, like locations of cooling centers and public housing, we should improve the way we store and configure those types of layers. Currently, a lot of this is hard-coded, so we need to abstract it out to a new sheet that defines each layer. Ultimately, I think we can continue to use the existing "Data Overlay" dropdown on the frontend (@Makosak to confirm this?), but we need to pull this list from a location outside of the codebase, and we also need to display a bit more information for each layer. Here's what I'm thinking we'll need to get this going,

- New google sheet, Data Overlays, with the following fields:
    - Display Name: name that shows up in the dropdown.
    - Description: description which will have to be added somewhere in the frontend.
    - Data Source: for now, this will be the name of a GeoJSON file that is stored in `/geojson/` (this is where these files are already stored)
    - Geometry Type: This will be `point` or `polygon` (we don't have any line layers at this time)
    - Symbol Prop: (optional) Name of the property on each feature that has the value needed to determine the symbol color.
    - Fill Color: (optional)
        - If no Symbol Prop is provided, this can be a single color
        - If a Symbol Prop is provided, this value should be modeled after the existing color scales for these layers. For example (redlining):
        ```
        {
            A: [115, 169, 77],
            B: [52, 172, 198],
            C: [219, 207, 0],
            D: [226, 77, 90],
        }
        ```
        - If no Fill Color is provided, there will be no fill on the symbol (necessary for a layer with only outlines, like the neighborhood layer
    - Line Color: (optional)
        - If a Line Color is provided, use it for the outline of a point/circle, or for the outline of a polygon
    - Line Width: (optional)
        - Only draw an outline on a polygon or circle/point if a Line Width is provided

This symbolizing can get complicated pretty quick, but I think we'll need all of this information (at least) just to replicate what we already have on the map.

Once this sheet is created with one or two test layers, it should be built and loaded alongside other sheets like columns.json and used to populate the `overlayLayers` list in MapSection.js.

Keep in mind, I'm sure we'll still need to handle some exceptional layers, so it's fine if something needs to be appended to that list for now.

**Comment by bodom0015** [comment]
Some ideas that have come up while trying to implement a first draft of this:
* Public Housing has a TON of different labels.. may need to consolidate/sub-categorize these to make them work in this new pattern
* Request: support filtering on different data points
* Request: show pop-up with more information - how to configure which fields should be shown? Can maybe make existing CC tooltip more generic
