### ISSUE TITLE
GeoJson error in console

### ISSUE THREAD

**Issue by mradamcox** [healthyregions/chicago-environment-explorer#75]
Seeing the following in the console, when I load the map page. Strangely, sometimes it errors out the full 

![image](https://github.com/GeoDaCenter/chicago-environment-explorer/assets/10427268/0e2d4a21-ff64-417a-a181-c68843fec203)

Sometimes the map finishes loading properly, other times it does not, and the histogram panel stays blank. Clicking in the histogram panel causes the `TypeError` shown the screenshot to appear.

**Comment by mradamcox** [comment]
This is actually two different errors. @mukeshchugani10 will put in a fix for the `k.current` issue mentioned above (which presents differently in Chrome but does exist in that browser as well), and after that is applied we can go back and look for the GeoJSON error.

**Comment by mradamcox** [comment]
@bodom0015 I'm still seeing this error. It certainly must not be critical, but could you look into it? It's probably just a missing property or something.

**Comment by bodom0015** [comment]
@mradamcox I don't see this same error in Chrome, but I do see other errors that also seem innocuous.
It looks like you're using Firefox, is that right?

I do see this mentioned at the bottom of the list here in regards to Firefox:
https://github.com/visgl/deck.gl/issues/2892#issuecomment-481031664

Digging further to see if there is a fix somewhere (possibly in a newer version of DeckGL?)

**Comment by mradamcox** [comment]
Yup, on Firefox, I see there's no error with Chrome or Edge. I'd say look a little more but otherwise let's just close this. That issue links to something fixed in v7, but we are at 8 already so seems like it may be something else. Not a big deal really.

**Comment by mradamcox** [comment]
Closing this now, seems like it's an edge case in Firefox, and it doesn't actually affect the page performance or display anyway. Thanks for looking into it @bodom0015 .
