### ISSUE TITLE
Home page— Footer Lab Logo

### ISSUE THREAD

**Issue by MarcAst24** [healthyregions/chicago-environment-explorer#94]
**Issue**: In the footer, the lab logo does not look appropriately placed for the organization logo

**Recommendation**: Right-align the lab logo in the footer

**Rationale**: This way, the logo would look separate from links and more like an organization logo

**Comment by Makosak** [comment]
Add the DePaul logo too, as they brought in funding for this round

**Comment by bodom0015** [comment]
@Makosak It looks like we already have a DePaul logo in the carousel? Did we want another logo here, or maybe a different one?

![Screenshot_2024-06-25_at_4_16_03_PM](https://github.com/healthyregions/chicago-environment-explorer/assets/1413653/745235c9-2810-48b6-8a11-e527471d3483)

**Comment by Makosak** [comment]
I was thinking the DePaul logo would go in the footer logo, next to the HEROP lab's, as they brought in funding for the project. Both of these should also be right adjusted, as right now the HEROP logo is oddly in the middle-ish?

![Screen Shot 2024-06-25 at 7 08 40 PM](https://github.com/healthyregions/chicago-environment-explorer/assets/4277692/03b3db43-bb97-435d-9a89-71f04c400684)
